# Generated by Django 5.1.6 on 2025-03-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='total_ids',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
