# Generated by Django 5.1.6 on 2025-03-18 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_maker', '0002_endpoint_total_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField()),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_maker.endpoint')),
            ],
        ),
    ]
