# Generated by Django 5.1.6 on 2025-03-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_maker', '0003_baserawdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=100, unique=True)),
                ('id_int', models.IntegerField(unique=True)),
                ('raw_data', models.JSONField()),
                ('name_in_data', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=100, unique=True)),
                ('id_int', models.IntegerField(unique=True)),
                ('raw_data', models.JSONField()),
                ('name_in_data', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=100, unique=True)),
                ('id_int', models.IntegerField(unique=True)),
                ('raw_data', models.JSONField()),
                ('name_in_data', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoveRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=100, unique=True)),
                ('id_int', models.IntegerField(unique=True)),
                ('raw_data', models.JSONField()),
                ('name_in_data', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=100, unique=True)),
                ('id_int', models.IntegerField(unique=True)),
                ('raw_data', models.JSONField()),
                ('name_in_data', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeciesRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=100, unique=True)),
                ('id_int', models.IntegerField(unique=True)),
                ('raw_data', models.JSONField()),
                ('name_in_data', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BaseRawData',
        ),
    ]
