# Generated by Django 5.1.6 on 2025-03-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_maker', '0004_abilityrawdata_formrawdata_itemrawdata_moverawdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonFormRawData',
            fields=[
                ('id_str', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_int', models.IntegerField(unique=True)),
                ('raw_data', models.JSONField()),
                ('name_in_data', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokemonSpeciesRawData',
            fields=[
                ('id_str', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_int', models.IntegerField(unique=True)),
                ('raw_data', models.JSONField()),
                ('name_in_data', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FormRawData',
        ),
        migrations.DeleteModel(
            name='SpeciesRawData',
        ),
        migrations.RemoveField(
            model_name='abilityrawdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='itemrawdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='moverawdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pokemonrawdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='abilityrawdata',
            name='id_str',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='itemrawdata',
            name='id_str',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='moverawdata',
            name='id_str',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pokemonrawdata',
            name='id_str',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
