# Generated by Django 5.1.6 on 2025-03-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_maker', '0006_remove_endpoint_id_endpoint_ep_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='S2_AbilityRawData',
            fields=[
                ('id_str', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_int', models.IntegerField(unique=True)),
                ('name_in_data', models.CharField(max_length=100)),
                ('ep_url', models.CharField(max_length=200)),
                ('raw_data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='S2_ItemRawData',
            fields=[
                ('id_str', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_int', models.IntegerField(unique=True)),
                ('name_in_data', models.CharField(max_length=100)),
                ('ep_url', models.CharField(max_length=200)),
                ('raw_data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='S2_MoveRawData',
            fields=[
                ('id_str', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_int', models.IntegerField(unique=True)),
                ('name_in_data', models.CharField(max_length=100)),
                ('ep_url', models.CharField(max_length=200)),
                ('raw_data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='S2_PokemonFormRawData',
            fields=[
                ('id_str', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_int', models.IntegerField(unique=True)),
                ('name_in_data', models.CharField(max_length=100)),
                ('ep_url', models.CharField(max_length=200)),
                ('raw_data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='S2_PokemonRawData',
            fields=[
                ('id_str', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_int', models.IntegerField(unique=True)),
                ('name_in_data', models.CharField(max_length=100)),
                ('ep_url', models.CharField(max_length=200)),
                ('raw_data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='S2_PokemonSpeciesRawData',
            fields=[
                ('id_str', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id_int', models.IntegerField(unique=True)),
                ('name_in_data', models.CharField(max_length=100)),
                ('ep_url', models.CharField(max_length=200)),
                ('raw_data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Endpoint',
            new_name='S1_Endpoint',
        ),
        migrations.DeleteModel(
            name='AbilityRawData',
        ),
        migrations.DeleteModel(
            name='ItemRawData',
        ),
        migrations.DeleteModel(
            name='MoveRawData',
        ),
        migrations.DeleteModel(
            name='PokemonFormRawData',
        ),
        migrations.DeleteModel(
            name='PokemonRawData',
        ),
        migrations.DeleteModel(
            name='PokemonSpeciesRawData',
        ),
    ]
