# Generated by Django 5.1.6 on 2025-03-19 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_maker', '0007_s2_abilityrawdata_s2_itemrawdata_s2_moverawdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3_MonsterIndividual',
            fields=[
                ('monster_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_maker.s2_pokemonrawdata')),
                ('pokemon_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_maker.s2_pokemonformrawdata')),
                ('pokemon_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_maker.s2_pokemonspeciesrawdata')),
            ],
        ),
    ]
