# Generated by Django 5.1.6 on 2025-03-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_maker', '0009_rename_monster_id_s3_monsterindividual_monster_id_str_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='s2_abilityrawdata',
            name='json_exist',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='s2_itemrawdata',
            name='json_exist',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='s2_moverawdata',
            name='json_exist',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='s2_pokemonformrawdata',
            name='json_exist',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='s2_pokemonrawdata',
            name='json_exist',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='s2_pokemonspeciesrawdata',
            name='json_exist',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
