# Generated by Django 5.1.6 on 2025-03-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_maker', '0010_s2_abilityrawdata_json_exist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s3_monsterindividual',
            old_name='pokemon_raw_data',
            new_name='pokemon',
        ),
        migrations.RenameField(
            model_name='s3_monsterindividual',
            old_name='pokemon_form_raw_data',
            new_name='pokemon_form',
        ),
        migrations.RenameField(
            model_name='s3_monsterindividual',
            old_name='pokemon_species_raw_data',
            new_name='pokemon_species',
        ),
        migrations.AddField(
            model_name='s3_monsterindividual',
            name='monster_id_int',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='s3_monsterindividual',
            name='monster_id_str',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
