# Generated by Django 5.1.6 on 2025-03-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_maker', '0011_rename_pokemon_raw_data_s3_monsterindividual_pokemon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3_monsterindividual',
            name='monster_id_int',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='s3_monsterindividual',
            name='monster_id_str',
            field=models.CharField(max_length=100),
        ),
    ]
