# Generated by Django 5.1.6 on 2025-03-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_maker', '0012_alter_s3_monsterindividual_monster_id_int_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3_monsterindividual',
            name='exist_all_json',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='s3_monsterindividual',
            name='pokemon_form_short_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='s3_monsterindividual',
            name='pokemon_short_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='s3_monsterindividual',
            name='pokemon_species_short_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
