# Generated by Django 5.1.6 on 2025-03-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_maker", "0013_s3_monsterindividual_exist_all_json_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="S4_FinalMonsterIndividual",
            fields=[
                (
                    "monster_id_int",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("monster_id_str", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                ("jp_name_from_species", models.CharField(max_length=100)),
                ("jp_name_from_pokemon", models.CharField(max_length=100)),
                ("jp_name_from_form", models.CharField(max_length=100)),
                ("name_from_species", models.CharField(max_length=100)),
                ("name_from_pokemon", models.CharField(max_length=100)),
                ("name_from_form", models.CharField(max_length=100)),
                ("type_1", models.CharField(max_length=100)),
                ("type_2", models.CharField(max_length=100)),
                ("stats_h", models.IntegerField(blank=True, null=True)),
                ("stats_a", models.IntegerField(blank=True, null=True)),
                ("stats_b", models.IntegerField(blank=True, null=True)),
                ("stats_c", models.IntegerField(blank=True, null=True)),
                ("stats_d", models.IntegerField(blank=True, null=True)),
                ("stats_s", models.IntegerField(blank=True, null=True)),
                ("ability_1", models.CharField(max_length=100)),
                ("ability_2", models.CharField(max_length=100)),
                ("ability_3", models.CharField(max_length=100)),
                ("flavor_text", models.CharField(max_length=100)),
                ("first_generation", models.CharField(max_length=100)),
                (
                    "is_normal",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("is_baby", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "is_legendary",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_mythical",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("egg_group_1", models.CharField(default=None, max_length=100)),
                ("egg_group_2", models.CharField(default=None, max_length=100)),
                ("sprites_json", models.JSONField(blank=True, null=True)),
                ("cries_url", models.CharField(max_length=100)),
            ],
        ),
    ]
