# Generated by Django 5.1.6 on 2025-03-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_maker", "0014_s4_finalmonsterindividual"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="S4_FinalMonsterIndividual",
            new_name="S4_SemiFinalMonsterIndividual",
        ),
    ]
