# Generated by Django 5.1.6 on 2025-03-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_maker",
            "0015_rename_s4_finalmonsterindividual_s4_semifinalmonsterindividual",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="S5_DemoMonseterIndividual",
            fields=[
                (
                    "monster_id_int",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("monster_id_str", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="S6_ProcessedPokemon",
            fields=[
                (
                    "monster_id_int",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "monster_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "monster_name_jp",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("form_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "form_name_jp",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("types", models.JSONField(blank=True, null=True)),
                ("abilities", models.JSONField(blank=True, null=True)),
                ("flavor_text", models.TextField(blank=True, null=True)),
                ("egg_groups", models.JSONField(blank=True, null=True)),
                ("stats", models.JSONField(blank=True, null=True)),
                ("pokedex_number", models.JSONField(blank=True, null=True)),
                ("is_baby", models.BooleanField(default=False)),
                ("is_legendary", models.BooleanField(default=False)),
                ("is_mythical", models.BooleanField(default=False)),
            ],
        ),
    ]
