# Generated by Django 5.1.6 on 2025-03-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_maker", "0016_s5_demomonseterindividual_s6_processedpokemon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="s6_processedpokemon",
            name="abilities",
        ),
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="ability_1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="ability_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="ability_3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="is_normal",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="s6_processedpokemon",
            name="flavor_text",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
