# Generated by Django 5.1.6 on 2025-03-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_maker", "0017_remove_s6_processedpokemon_abilities_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="s6_processedpokemon",
            name="types",
        ),
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="type_1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="type_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
