# Generated by Django 5.1.6 on 2025-03-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_maker", "0018_remove_s6_processedpokemon_types_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="front_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
