# Generated by Django 5.1.6 on 2025-03-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_maker", "0019_s6_processedpokemon_front_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="pokemon_id_str",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
