# Generated by Django 5.1.6 on 2025-03-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_maker", "0020_s6_processedpokemon_pokemon_id_str"),
    ]

    operations = [
        migrations.RenameField(
            model_name="s6_processedpokemon",
            old_name="pokemon_id_str",
            new_name="monster_id_str",
        ),
    ]
