# Generated by Django 5.1.6 on 2025-03-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_maker", "0021_rename_pokemon_id_str_s6_processedpokemon_monster_id_str"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="s6_processedpokemon",
            name="stats",
        ),
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="stat_a",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="stat_b",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="stat_c",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="stat_d",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="stat_h",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="stat_s",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="stat_t",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
