# Generated by Django 5.1.6 on 2025-03-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_maker", "0022_remove_s6_processedpokemon_stats_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="s4_semifinalmonsterindividual",
            old_name="stats_a",
            new_name="stat_a",
        ),
    ]
