# Generated by Django 5.1.6 on 2025-03-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_maker",
            "0024_rename_stats_b_s4_semifinalmonsterindividual_stat_b_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="S4_SemiFinalMonsterIndividual",
        ),
    ]
