# Generated by Django 5.1.6 on 2025-03-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_maker", "0025_delete_s4_semifinalmonsterindividual"),
    ]

    operations = [
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="front_url_exist",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
