# Generated by Django 5.1.6 on 2025-03-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_maker", "0026_s6_processedpokemon_front_url_exist"),
    ]

    operations = [
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="national_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
