# Generated by Django 5.1.6 on 2025-03-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_maker", "0027_s6_processedpokemon_national_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="is_genera",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
