# Generated by Django 5.1.6 on 2025-03-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_maker", "0028_s6_processedpokemon_is_genera"),
    ]

    operations = [
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="is_gmax",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="s6_processedpokemon",
            name="is_mega",
            field=models.BooleanField(default=False),
        ),
    ]
